#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the ClassGenerator.ttinclude code generation file.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Data;
using System.Linq;
using System.Linq.Expressions;
using System.Data.Common;
using System.Collections.Generic;
using Telerik.OpenAccess;
using Telerik.OpenAccess.Metadata;
using Telerik.OpenAccess.Data.Common;
using Telerik.OpenAccess.Metadata.Fluent;
using Telerik.OpenAccess.Metadata.Fluent.Advanced;
using Corrida_DB;

namespace Corrida_DB	
{
	public partial class Corrida
	{
		private int _id;
		public virtual int Id
		{
			get
			{
				return this._id;
			}
			set
			{
				this._id = value;
			}
		}
		
		private string _nome;
		public virtual string Nome
		{
			get
			{
				return this._nome;
			}
			set
			{
				this._nome = value;
			}
		}
		
		private decimal? _valor;
		public virtual decimal? Valor
		{
			get
			{
				return this._valor;
			}
			set
			{
				this._valor = value;
			}
		}
		
		private int? _distancia;
		public virtual int? Distancia
		{
			get
			{
				return this._distancia;
			}
			set
			{
				this._distancia = value;
			}
		}
		
		private DateTime? _dataCorrida;
		public virtual DateTime? DataCorrida
		{
			get
			{
				return this._dataCorrida;
			}
			set
			{
				this._dataCorrida = value;
			}
		}
		
		private int? _id_Local;
		public virtual int? Id_Local
		{
			get
			{
				return this._id_Local;
			}
			set
			{
				this._id_Local = value;
			}
		}
		
		private Local _local;
		public virtual Local Local
		{
			get
			{
				return this._local;
			}
			set
			{
				this._local = value;
			}
		}
		
	}
}
#pragma warning restore 1591
