#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the ContextGenerator.ttinclude code generation file.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Data;
using System.Linq;
using System.Linq.Expressions;
using System.Data.Common;
using System.Collections.Generic;
using Telerik.OpenAccess;
using Telerik.OpenAccess.Metadata;
using Telerik.OpenAccess.Data.Common;
using Telerik.OpenAccess.Metadata.Fluent;
using Telerik.OpenAccess.Metadata.Fluent.Advanced;
using Corrida_DB;

namespace Corrida_DB	
{
	public partial class CorridaModel : OpenAccessContext, ICorridaModelUnitOfWork
	{
		private static string connectionStringName = @"Connection";
			
		private static BackendConfiguration backend = GetBackendConfiguration();
				
		private static MetadataSource metadataSource = XmlMetadataSource.FromAssemblyResource("EntitiesModel.rlinq");
		
		public CorridaModel()
			:base(connectionStringName, backend, metadataSource)
		{ }
		
		public CorridaModel(string connection)
			:base(connection, backend, metadataSource)
		{ }
		
		public CorridaModel(BackendConfiguration backendConfiguration)
			:base(connectionStringName, backendConfiguration, metadataSource)
		{ }
			
		public CorridaModel(string connection, MetadataSource metadataSource)
			:base(connection, backend, metadataSource)
		{ }
		
		public CorridaModel(string connection, BackendConfiguration backendConfiguration, MetadataSource metadataSource)
			:base(connection, backendConfiguration, metadataSource)
		{ }
			
		public IQueryable<Local> Locals 
		{
			get
			{
				return this.GetAll<Local>();
			}
		}
		
		public IQueryable<Corrida> Corridas 
		{
			get
			{
				return this.GetAll<Corrida>();
			}
		}
		
		public static BackendConfiguration GetBackendConfiguration()
		{
			BackendConfiguration backend = new BackendConfiguration();
			backend.Backend = "MySql";
			backend.ProviderName = "MySql.Data.MySqlClient";
		
			CustomizeBackendConfiguration(ref backend);
		
			return backend;
		}
		
		/// <summary>
		/// Allows you to customize the BackendConfiguration of CorridaModel.
		/// </summary>
		/// <param name="config">The BackendConfiguration of CorridaModel.</param>
		static partial void CustomizeBackendConfiguration(ref BackendConfiguration config);
		
	}
	
	public interface ICorridaModelUnitOfWork : IUnitOfWork
	{
		IQueryable<Local> Locals
		{
			get;
		}
		IQueryable<Corrida> Corridas
		{
			get;
		}
	}
}
#pragma warning restore 1591
