#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the ClassGenerator.ttinclude code generation file.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Data;
using System.Linq;
using System.Linq.Expressions;
using System.Data.Common;
using System.Collections.Generic;
using Telerik.OpenAccess;
using Telerik.OpenAccess.Metadata;
using Telerik.OpenAccess.Data.Common;
using Telerik.OpenAccess.Metadata.Fluent;
using Telerik.OpenAccess.Metadata.Fluent.Advanced;
using Corrida_DB;

namespace Corrida_DB	
{
	public partial class Local
	{
		private int _id;
		public virtual int Id
		{
			get
			{
				return this._id;
			}
			set
			{
				this._id = value;
			}
		}
		
		private string _cidade;
		public virtual string Cidade
		{
			get
			{
				return this._cidade;
			}
			set
			{
				this._cidade = value;
			}
		}
		
		private string _uf;
		public virtual string Uf
		{
			get
			{
				return this._uf;
			}
			set
			{
				this._uf = value;
			}
		}
		
		private IList<Corrida> _corridas = new List<Corrida>();
		public virtual IList<Corrida> Corridas
		{
			get
			{
				return this._corridas;
			}
		}
		
	}
}
#pragma warning restore 1591
